sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    port: 6379
    host: localhost
    database: 0
  wechat:
    appid: wx751441f05010e112
    secret: cbbe082eea835f2b690ac78aa0a8a933
#    mchid:
#    mch-serial-no:
#    private-key-file-path:
#    api-v3-key:
#    we-chat-pay-cert-file-path:
#    notify-url:
#    refund-notify-url: